[2023-07-29T23:05:09.706+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trainer.federate manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T23:05:09.712+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trainer.federate manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T23:05:09.713+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-29T23:05:09.721+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): federate> on 2023-07-29 22:26:04.728771+00:00
[2023-07-29T23:05:09.733+0000] {standard_task_runner.py:57} INFO - Started process 582854 to run task
[2023-07-29T23:05:09.735+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'trainer', 'federate', 'manual__2023-07-29T22:26:04.728771+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpm2_s42o6']
[2023-07-29T23:05:09.735+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask federate
[2023-07-29T23:05:09.775+0000] {task_command.py:410} INFO - Running <TaskInstance: trainer.federate manual__2023-07-29T22:26:04.728771+00:00 [running]> on host ip-172-31-37-30.ap-south-1.compute.internal
[2023-07-29T23:05:09.835+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trainer' AIRFLOW_CTX_TASK_ID='federate' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T22:26:04.728771+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T22:26:04.728771+00:00'
[2023-07-29T23:05:09.842+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:208 UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
[2023-07-29T23:05:09.843+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:223 UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
[2023-07-29T23:05:10.343+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/airflow/dags/train_dag.py", line 76, in federate_module
    train_loader, _, _ = loader.fetchLoaders()
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/fedgen/utils.py", line 57, in fetchLoaders
    trainDf = pd.read_csv(os.path.join(self.save_path, f'train_{self.worker}.csv'), index_col=False)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/GenAI-Rush/processed/train_worker2.csv'
[2023-07-29T23:05:10.353+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=trainer, task_id=federate, execution_date=20230729T222604, start_date=20230729T230509, end_date=20230729T230510
[2023-07-29T23:05:10.361+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task federate ([Errno 2] No such file or directory: '/home/ubuntu/GenAI-Rush/processed/train_worker2.csv'; 582854)
[2023-07-29T23:05:10.387+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T23:05:10.406+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
