[2023-07-29T22:49:56.494+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trainer.encrypt_data_worker2 manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T22:49:56.501+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trainer.encrypt_data_worker2 manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T22:49:56.501+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 5
[2023-07-29T22:49:56.513+0000] {taskinstance.py:1327} INFO - Executing <Task(BranchPythonOperator): encrypt_data_worker2> on 2023-07-29 22:26:04.728771+00:00
[2023-07-29T22:49:56.523+0000] {standard_task_runner.py:57} INFO - Started process 558572 to run task
[2023-07-29T22:49:56.525+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'trainer', 'encrypt_data_worker2', 'manual__2023-07-29T22:26:04.728771+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmp4eac_u_q']
[2023-07-29T22:49:56.525+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask encrypt_data_worker2
[2023-07-29T22:49:56.574+0000] {task_command.py:410} INFO - Running <TaskInstance: trainer.encrypt_data_worker2 manual__2023-07-29T22:26:04.728771+00:00 [running]> on host ip-172-31-37-30.ap-south-1.compute.internal
[2023-07-29T22:49:56.642+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trainer' AIRFLOW_CTX_TASK_ID='encrypt_data_worker2' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T22:26:04.728771+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T22:26:04.728771+00:00'
[2023-07-29T22:49:56.704+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:208 UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
[2023-07-29T22:49:56.705+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:223 UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
[2023-07-29T22:49:57.208+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 215, in execute
    branch = super().execute(context)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/airflow/dags/train_dag.py", line 35, in encrypt_module
    train_loader, _, _ = loader.fetchLoaders()
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/fedgen/utils.py", line 62, in fetchLoaders
    valDf = pd.read_csv(os.path.join(self.save_path, f'valid_{self.worker}.csv'), index_col=False)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/GenAI-Rush/processed/valid_worker1.csv'
[2023-07-29T22:49:57.219+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=trainer, task_id=encrypt_data_worker2, execution_date=20230729T222604, start_date=20230729T224956, end_date=20230729T224957
[2023-07-29T22:49:57.232+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task encrypt_data_worker2 ([Errno 2] No such file or directory: '/home/ubuntu/GenAI-Rush/processed/valid_worker1.csv'; 558572)
[2023-07-29T22:49:57.298+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T22:49:57.323+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
