[2023-07-29T23:37:39.993+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trainer.test manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T23:37:39.999+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trainer.test manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T23:37:39.999+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-29T23:37:40.007+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): test> on 2023-07-29 22:26:04.728771+00:00
[2023-07-29T23:37:40.020+0000] {standard_task_runner.py:57} INFO - Started process 635394 to run task
[2023-07-29T23:37:40.022+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'trainer', 'test', 'manual__2023-07-29T22:26:04.728771+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpdjz6gvy8']
[2023-07-29T23:37:40.022+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask test
[2023-07-29T23:37:40.064+0000] {task_command.py:410} INFO - Running <TaskInstance: trainer.test manual__2023-07-29T22:26:04.728771+00:00 [running]> on host ip-172-31-37-30.ap-south-1.compute.internal
[2023-07-29T23:37:40.127+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trainer' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T22:26:04.728771+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T22:26:04.728771+00:00'
[2023-07-29T23:37:40.134+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:208 UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
[2023-07-29T23:37:40.135+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:223 UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
[2023-07-29T23:37:40.284+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/airflow/dags/train_dag.py", line 93, in test_module
    testObj.testClientModels()
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/fedgen/test.py", line 40, in testClientModels
    trainDataLoader, _, testDataLoader = loaderObj.fetchLoaders()
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/fedgen/utils.py", line 57, in fetchLoaders
    trainDf = pd.read_csv(os.path.join(self.save_path, f'train_{self.worker}.csv'), index_col=False)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../processed/train_worker2.csv'
[2023-07-29T23:37:40.294+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=trainer, task_id=test, execution_date=20230729T222604, start_date=20230729T233739, end_date=20230729T233740
[2023-07-29T23:37:40.302+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task test ([Errno 2] No such file or directory: '../processed/train_worker2.csv'; 635394)
[2023-07-29T23:37:40.354+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T23:37:40.372+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
